workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

include:
  - project: "${CI_PROJECT_ROOT_NAMESPACE}/shared-ci"
    ref: master
    file: "/deploy/stack.yml"
  - project: "${CI_PROJECT_ROOT_NAMESPACE}/shared-ci"
    ref: master
    file: "/build/docker.yml"

stages:
  - build
  - deploy

build:
  extends: .build_docker

deploy:
  extends: .deploy_stack
  needs: [build]
